/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, getSigningClientDefault, getQueryClientDefault, getMessageComposerDefault } from "./contractContextBase";
import { CwAdminFactoryClient } from "./CwAdminFactory.client.ts";
import { CwAdminFactoryQueryClient } from "./CwAdminFactory.client.ts";
import { CwAdminFactoryMessageComposer } from "./CwAdminFactory.message-composer.ts";
export class CwAdminFactory extends ContractBase {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }) {
    super(address, cosmWasmClient, signingCosmWasmClient);
  }

}