/**
* This file was automatically generated by @abstract-money/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

import { selectorFamily } from "recoil";
import { cosmWasmClient } from "./chain";
import { ExecuteMsg, Binary, InstantiateMsg, QueryMsg } from "./CwAdminFactory.types";
import { CwAdminFactoryQueryClient } from "./CwAdminFactory.client";
type QueryClientParams = {
  contractAddress: string;
};
export const queryClient = selectorFamily<CwAdminFactoryQueryClient, QueryClientParams>({
  key: "cwAdminFactoryQueryClient",
  get: ({
    contractAddress
  }) => ({
    get
  }) => {
    const client = get(cosmWasmClient);
    return new CwAdminFactoryQueryClient(client, contractAddress);
  }
});