/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, getSigningClientDefault, getQueryClientDefault, getMessageComposerDefault } from "./contractContextBase";
import { CwCodeIdRegistryClient } from "./CwCodeIdRegistry.client.ts";
import { CwCodeIdRegistryQueryClient } from "./CwCodeIdRegistry.client.ts";
import { CwCodeIdRegistryMessageComposer } from "./CwCodeIdRegistry.message-composer.ts";
export class CwCodeIdRegistry extends ContractBase {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }) {
    super(address, cosmWasmClient, signingCosmWasmClient);
  }

}