/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor, getSigningClientDefault, getQueryClientDefault, getMessageComposerDefault } from "./contractContextBase";
import { CwSingleClient } from "./CwSingle.client";
import { CwSingleQueryClient } from "./CwSingle.client";
import { CwSingleMessageComposer } from "./CwSingle.message-composer";
export class CwSingle extends ContractBase {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient);
  }

  getSigningClient(contractAddr) {
    return getSigningClientDefault(this, contractAddr, CwSingleClient);
  }

  getQueryClient(contractAddr) {
    return getQueryClientDefault(this, contractAddr, CwSingleQueryClient);
  }

  getMessageComposer(contractAddr) {
    return getMessageComposerDefault(this, contractAddr, CwSingleMessageComposer);
  }

}