/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, getSigningClientDefault, getQueryClientDefault, getMessageComposerDefault } from "./contractContextBase";
import { CwSingleClient } from "./CwSingle.client.ts";
import { CwSingleQueryClient } from "./CwSingle.client.ts";
import { CwSingleMessageComposer } from "./CwSingle.message-composer.ts";
export class CwSingle extends ContractBase {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }) {
    super(address, cosmWasmClient, signingCosmWasmClient);
  }

}