/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ExecuteMsg, Binary, InstantiateMsg, QueryMsg } from "./CwAdminFactory.types";
import { CamelCasedProperties } from "type-fest";
export abstract class CwAdminFactoryExecuteMessageBuilder {
  static instantiateContractWithSelfAdmin = ({
    codeId,
    instantiateMsg,
    label
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    instantiate_contract_with_self_admin: unknown;
  }>["instantiate_contract_with_self_admin"]>): ExecuteMsg => {
    return {
      instantiate_contract_with_self_admin: ({
        code_id: codeId,
        instantiate_msg: instantiateMsg,
        label
      } as const)
    };
  };
}