/**
* This file was automatically generated by @abstract-money/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  beneficiary: string;
  verifier: string;
}
export type ExecuteMsg = {
  release: {};
} | {
  cpu_loop: {};
} | {
  storage_loop: {};
} | {
  memory_loop: {};
} | {
  message_loop: {};
} | {
  allocate_large_memory: {
    pages: number;
  };
} | {
  panic: {};
} | {
  user_errors_in_api_calls: {};
};
export type QueryMsg = {
  verifier: {};
} | {
  other_balance: {
    address: string;
  };
} | {
  recurse: {
    depth: number;
    work: number;
  };
} | {
  get_int: {};
};
export interface MigrateMsg {
  verifier: string;
}
export type SudoMsg = {
  steal_funds: {
    amount: Coin[];
    recipient: string;
  };
};
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface IntResponse {
  int: number;
}
export interface AllBalanceResponse {
  amount: Coin[];
  [k: string]: unknown;
}
export type Binary = string;
export interface RecurseResponse {
  hashed: Binary;
}
export interface VerifierResponse {
  verifier: string;
}