/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  [k: string]: unknown;
}
export type ExecuteMsg = {
  argon2: {
    mem_cost: number;
    time_cost: number;
  };
} | {
  mirror_env: {};
};
export type QueryMsg = {
  mirror_env: {};
};