/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery } from "react-query";
import { InstantiateMsg, ExecuteMsg, QueryMsg } from "./CyberPunk.types";
import { CyberPunkQueryClient } from "./CyberPunk.client";
export interface CyberPunkReactQuery<TResponse, TData = TResponse> {
  client: CyberPunkQueryClient;
  options?: UseQueryOptions<TResponse, Error, TData>;
}
export interface CyberPunkMirrorEnvQuery<TData> extends CyberPunkReactQuery<MirrorEnvResponse, TData> {}
export function useCyberPunkMirrorEnvQuery<TData = MirrorEnvResponse>({
  client,
  options
}: CyberPunkMirrorEnvQuery<TData>) {
  return useQuery<MirrorEnvResponse, Error, TData>(["cyberPunkMirrorEnv", client.contractAddress], () => client.mirrorEnv(), options);
}