/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { selectorFamily } from "recoil";
import { cosmWasmClient } from "./chain";
import { InstantiateMsg, ExecuteMsg, QueryMsg, Timestamp, Uint64, Addr, Env, BlockInfo, ContractInfo, TransactionInfo } from "./CyberPunk.types";
import { CyberPunkQueryClient } from "./CyberPunk.client";
type QueryClientParams = {
  contractAddress: string;
};
export const queryClient = selectorFamily<CyberPunkQueryClient, QueryClientParams>({
  key: "cyberPunkQueryClient",
  get: ({
    contractAddress
  }) => ({
    get
  }) => {
    const client = get(cosmWasmClient);
    return new CyberPunkQueryClient(client, contractAddress);
  }
});
export const mirrorEnvSelector = selectorFamily<Env, QueryClientParams & {
  params: Parameters<CyberPunkQueryClient["mirrorEnv"]>;
}>({
  key: "cyberPunkMirrorEnv",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.mirrorEnv(...params);
  }
});