/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { AppExecuteMsg, AppModuleExecuteMsgBuilder } from "@abstract-money/abstract.js";
import { InstantiateMsg, Member, ExecuteMsg, QueryMsg, AdminResponse, HooksResponse, MemberListResponse, MemberResponse, TotalWeightResponse } from "./Cw4Group.types";
export interface Cw4GroupMessage {
  contractAddress: string;
  sender: string;
  updateAdmin: ({
    admin
  }: {
    admin?: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateMembers: ({
    add,
    remove
  }: {
    add: Member[];
    remove: string[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  addHook: ({
    addr
  }: {
    addr: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  removeHook: ({
    addr
  }: {
    addr: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class Cw4GroupMessageComposer implements Cw4GroupMessage {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateAdmin = this.updateAdmin.bind(this);
    this.updateMembers = this.updateMembers.bind(this);
    this.addHook = this.addHook.bind(this);
    this.removeHook = this.removeHook.bind(this);
  }

  updateAdmin = ({
    admin
  }: {
    admin?: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    const msg = {
      update_admin: {
        admin
      }
    };
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify(msg)),
        funds: _funds
      })
    };
  };
  updateMembers = ({
    add,
    remove
  }: {
    add: Member[];
    remove: string[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    const msg = {
      update_members: {
        add,
        remove
      }
    };
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify(msg)),
        funds: _funds
      })
    };
  };
  addHook = ({
    addr
  }: {
    addr: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    const msg = {
      add_hook: {
        addr
      }
    };
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify(msg)),
        funds: _funds
      })
    };
  };
  removeHook = ({
    addr
  }: {
    addr: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    const msg = {
      remove_hook: {
        addr
      }
    };
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify(msg)),
        funds: _funds
      })
    };
  };
}