/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { selectorFamily } from "recoil";
import { cosmWasmClient } from "./chain";
import { DumpResponse, Group, ExecuteMsg, InstantiateMsg, Addr, ListAddressesResponse, ListGroupsResponse, QueryMsg } from "./CwNamedGroupsContract";
import { CwNamedGroupsQueryClient } from "./CwNamedGroupsContract.ts";
type QueryClientParams = {
  contractAddress: string;
};
export const queryClient = selectorFamily<CwNamedGroupsQueryClient, QueryClientParams>({
  key: "cwNamedGroupsQueryClient",
  get: ({
    contractAddress
  }) => ({
    get
  }) => {
    const client = get(cosmWasmClient);
    return new CwNamedGroupsQueryClient(client, contractAddress);
  }
});
export const dumpSelector = selectorFamily<DumpResponse, QueryClientParams & {
  params: Parameters<CwNamedGroupsQueryClient["dump"]>;
}>({
  key: "cwNamedGroupsDump",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.dump(...params);
  }
});
export const listGroupsSelector = selectorFamily<ListGroupsResponse, QueryClientParams & {
  params: Parameters<CwNamedGroupsQueryClient["listGroups"]>;
}>({
  key: "cwNamedGroupsListGroups",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.listGroups(...params);
  }
});
export const listAddressesSelector = selectorFamily<ListAddressesResponse, QueryClientParams & {
  params: Parameters<CwNamedGroupsQueryClient["listAddresses"]>;
}>({
  key: "cwNamedGroupsListAddresses",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.listAddresses(...params);
  }
});
export const isAddressInGroupSelector = selectorFamily<IsAddressInGroupResponse, QueryClientParams & {
  params: Parameters<CwNamedGroupsQueryClient["isAddressInGroup"]>;
}>({
  key: "cwNamedGroupsIsAddressInGroup",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.isAddressInGroup(...params);
  }
});