/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery } from "react-query";
import { Addr, PaymentInfo, Uint128, ConfigResponse, ExecuteMsg, Binary, Cw20ReceiveMsg, GetRegistrationResponse, Registration, InfoForCodeIdResponse, InstantiateMsg, ListRegistrationsResponse, QueryMsg, ReceiveMsg } from "./CwCodeIdRegistry.types";
import { CwCodeIdRegistryQueryClient } from "./CwCodeIdRegistry.client";
export interface CwCodeIdRegistryReactQuery<TResponse> {
  client: CwCodeIdRegistryQueryClient;
  options?: UseQueryOptions<TResponse, Error, TResponse, (string | undefined)[]>;
}
export interface CwCodeIdRegistryListRegistrationsQuery extends CwCodeIdRegistryReactQuery<ListRegistrationsResponse> {
  args: {
    chainId: string;
    name: string;
  };
}
export function useCwCodeIdRegistryListRegistrationsQuery({
  client,
  args,
  options
}: CwCodeIdRegistryListRegistrationsQuery) {
  return useQuery<ListRegistrationsResponse, Error, ListRegistrationsResponse, (string | undefined)[]>(["cwCodeIdRegistryListRegistrations", client.contractAddress, JSON.stringify(args)], () => client.listRegistrations({
    chainId: args.chainId,
    name: args.name
  }), options);
}
export interface CwCodeIdRegistryInfoForCodeIdQuery extends CwCodeIdRegistryReactQuery<InfoForCodeIdResponse> {
  args: {
    chainId: string;
    codeId: number;
  };
}
export function useCwCodeIdRegistryInfoForCodeIdQuery({
  client,
  args,
  options
}: CwCodeIdRegistryInfoForCodeIdQuery) {
  return useQuery<InfoForCodeIdResponse, Error, InfoForCodeIdResponse, (string | undefined)[]>(["cwCodeIdRegistryInfoForCodeId", client.contractAddress, JSON.stringify(args)], () => client.infoForCodeId({
    chainId: args.chainId,
    codeId: args.codeId
  }), options);
}
export interface CwCodeIdRegistryGetRegistrationQuery extends CwCodeIdRegistryReactQuery<GetRegistrationResponse> {
  args: {
    chainId: string;
    name: string;
    version?: string;
  };
}
export function useCwCodeIdRegistryGetRegistrationQuery({
  client,
  args,
  options
}: CwCodeIdRegistryGetRegistrationQuery) {
  return useQuery<GetRegistrationResponse, Error, GetRegistrationResponse, (string | undefined)[]>(["cwCodeIdRegistryGetRegistration", client.contractAddress, JSON.stringify(args)], () => client.getRegistration({
    chainId: args.chainId,
    name: args.name,
    version: args.version
  }), options);
}
export interface CwCodeIdRegistryConfigQuery extends CwCodeIdRegistryReactQuery<ConfigResponse> {}
export function useCwCodeIdRegistryConfigQuery({
  client,
  options
}: CwCodeIdRegistryConfigQuery) {
  return useQuery<ConfigResponse, Error, ConfigResponse, (string | undefined)[]>(["cwCodeIdRegistryConfig", client.contractAddress], () => client.config(), options);
}