/**
* This file was automatically generated by @abstract-money/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

import { Decimal, InstantiateMsg, ExecuteMsg, Uint128, AssetInfoBaseForString, AssetBaseForString, QueryMsg, MigrateMsg, StateResponse } from "./Etf.types";
import { CamelCasedProperties } from "type-fest";
export abstract class EtfExecuteMsgBuilder {
  static provideLiquidity = ({
    asset
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    provide_liquidity: unknown;
  }>["provide_liquidity"]>): ExecuteMsg => {
    return {
      provide_liquidity: ({
        asset
      } as const)
    };
  };
  static setFee = ({
    fee
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    set_fee: unknown;
  }>["set_fee"]>): ExecuteMsg => {
    return {
      set_fee: ({
        fee
      } as const)
    };
  };
}
export abstract class EtfQueryMsgBuilder {
  static state = (): QueryMsg => {
    return {
      state: ({} as const)
    };
  };
}