/**
* This file was automatically generated by @abstract-money/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export interface InstantiateMsg {
  fee: Decimal;
  provider_addr: string;
  token_code_id: number;
  token_name?: string | null;
  token_symbol?: string | null;
}
export type ExecuteMsg = {
  provide_liquidity: {
    asset: AssetBaseForString;
  };
} | {
  set_fee: {
    fee: Decimal;
  };
};
export type Uint128 = string;
export type AssetInfoBaseForString = {
  native: string;
} | {
  cw20: string;
};
export interface AssetBaseForString {
  amount: Uint128;
  info: AssetInfoBaseForString;
}
export type QueryMsg = {
  state: {};
};
export interface MigrateMsg {
  [k: string]: unknown;
}
export interface StateResponse {
  fee: Decimal;
  liquidity_token: string;
}