/**
* This file was automatically generated by @abstract-money/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

import { selectorFamily } from "recoil";
import { cosmWasmClient } from "./chain";
import { Decimal, InstantiateMsg, ExecuteMsg, Uint128, AssetInfoBaseForString, AssetBaseForString, QueryMsg, MigrateMsg, StateResponse } from "./Etf.types";
import { EtfQueryClient } from "./Etf.client";
type QueryClientParams = {
  contractAddress: string;
};
export const queryClient = selectorFamily<EtfQueryClient, QueryClientParams>({
  key: "etfQueryClient",
  get: ({
    contractAddress
  }) => ({
    get
  }) => {
    const client = get(cosmWasmClient);
    return new EtfQueryClient(client, contractAddress);
  }
});
export const stateSelector = selectorFamily<StateResponse, QueryClientParams & {
  params: Parameters<EtfQueryClient["state"]>;
}>({
  key: "etfState",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.state(...params);
  }
});