/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Addr, PaymentInfo, Uint128, ConfigResponse, ExecuteMsg, Binary, Cw20ReceiveMsg, GetRegistrationResponse, Registration, InfoForCodeIdResponse, InstantiateMsg, ListRegistrationsResponse, QueryMsg, ReceiveMsg } from "./CwCodeIdRegistry.types";
export abstract class CwCodeIdRegistryExecuteMsgBuilder {
  static receive = ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }): ExecuteMsg => {
    return {
      receive: ({
        amount,
        msg,
        sender
      } as const)
    };
  };
  static register = ({
    chainId,
    checksum,
    codeId,
    name,
    version
  }: {
    chainId: string;
    checksum: string;
    codeId: number;
    name: string;
    version: string;
  }): ExecuteMsg => {
    return {
      register: ({
        chain_id: chainId,
        checksum,
        code_id: codeId,
        name,
        version
      } as const)
    };
  };
  static setOwner = ({
    chainId,
    name,
    owner
  }: {
    chainId: string;
    name: string;
    owner?: string;
  }): ExecuteMsg => {
    return {
      set_owner: ({
        chain_id: chainId,
        name,
        owner
      } as const)
    };
  };
  static unregister = ({
    chainId,
    codeId
  }: {
    chainId: string;
    codeId: number;
  }): ExecuteMsg => {
    return {
      unregister: ({
        chain_id: chainId,
        code_id: codeId
      } as const)
    };
  };
  static updateConfig = ({
    admin,
    paymentInfo
  }: {
    admin?: string;
    paymentInfo?: PaymentInfo;
  }): ExecuteMsg => {
    return {
      update_config: ({
        admin,
        payment_info: paymentInfo
      } as const)
    };
  };
}
export abstract class CwCodeIdRegistryQueryMsgBuilder {
  static config = (): QueryMsg => {
    return {
      config: ({} as const)
    };
  };
  static getRegistration = ({
    chainId,
    name,
    version
  }: {
    chainId: string;
    name: string;
    version?: string;
  }): QueryMsg => {
    return {
      get_registration: ({
        chain_id: chainId,
        name,
        version
      } as const)
    };
  };
  static infoForCodeId = ({
    chainId,
    codeId
  }: {
    chainId: string;
    codeId: number;
  }): QueryMsg => {
    return {
      info_for_code_id: ({
        chain_id: chainId,
        code_id: codeId
      } as const)
    };
  };
  static listRegistrations = ({
    chainId,
    name
  }: {
    chainId: string;
    name: string;
  }): QueryMsg => {
    return {
      list_registrations: ({
        chain_id: chainId,
        name
      } as const)
    };
  };
}