/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { AdminAddrResponse, CodeIdResponse, CodeIdType, Uint128, Binary, CreateWalletMsg, Guardians, MultiSig, Coin, Cw20Coin, ExecuteMsg, Addr, ProxyMigrationTxMsg, WalletAddr, CanonicalAddr, RelayTransaction, FeeResponse, GovecAddrResponse, InstantiateMsg, QueryMsg, WalletQueryPrefix, Duration, StakingOptions, WalletInfo, ContractVersion, WalletsOfResponse, WalletsResponse } from "./Factory.types";
export abstract class FactoryExecuteMsgBuilder {
  static createWallet = ({
    createWalletMsg
  }: {
    createWalletMsg: CreateWalletMsg;
  }): ExecuteMsg => {
    return {
      create_wallet: ({
        create_wallet_msg: createWalletMsg
      } as const)
    };
  };
  static updateProxyUser = ({
    newUser,
    oldUser
  }: {
    newUser: Addr;
    oldUser: Addr;
  }): ExecuteMsg => {
    return {
      update_proxy_user: ({
        new_user: newUser,
        old_user: oldUser
      } as const)
    };
  };
  static migrateWallet = ({
    migrationMsg,
    walletAddress
  }: {
    migrationMsg: ProxyMigrationTxMsg;
    walletAddress: WalletAddr;
  }): ExecuteMsg => {
    return {
      migrate_wallet: ({
        migration_msg: migrationMsg,
        wallet_address: walletAddress
      } as const)
    };
  };
  static updateCodeId = ({
    newCodeId,
    ty
  }: {
    newCodeId: number;
    ty: CodeIdType;
  }): ExecuteMsg => {
    return {
      update_code_id: ({
        new_code_id: newCodeId,
        ty
      } as const)
    };
  };
  static updateWalletFee = ({
    newFee
  }: {
    newFee: Coin;
  }): ExecuteMsg => {
    return {
      update_wallet_fee: ({
        new_fee: newFee
      } as const)
    };
  };
  static updateGovecAddr = ({
    addr
  }: {
    addr: string;
  }): ExecuteMsg => {
    return {
      update_govec_addr: ({
        addr
      } as const)
    };
  };
  static updateAdmin = ({
    addr
  }: {
    addr: string;
  }): ExecuteMsg => {
    return {
      update_admin: ({
        addr
      } as const)
    };
  };
}
export abstract class FactoryQueryMsgBuilder {
  static wallets = ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: WalletQueryPrefix;
  }): QueryMsg => {
    return {
      wallets: ({
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static walletsOf = ({
    limit,
    startAfter,
    user
  }: {
    limit?: number;
    startAfter?: string;
    user: string;
  }): QueryMsg => {
    return {
      wallets_of: ({
        limit,
        start_after: startAfter,
        user
      } as const)
    };
  };
  static codeId = ({
    ty
  }: {
    ty: CodeIdType;
  }): QueryMsg => {
    return {
      code_id: ({
        ty
      } as const)
    };
  };
  static fee = (): QueryMsg => {
    return {
      fee: ({} as const)
    };
  };
  static govecAddr = (): QueryMsg => {
    return {
      govec_addr: ({} as const)
    };
  };
  static adminAddr = (): QueryMsg => {
    return {
      admin_addr: ({} as const)
    };
  };
}