/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { FactoryClient, FactoryQueryClient } from "./Factory.client";
import { FactoryMsgComposer } from "./Factory.message-composer";
export class Factory extends ContractBase<FactoryClient, FactoryQueryClient, FactoryMsgComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, FactoryClient, FactoryQueryClient, FactoryMsgComposer);
  }

}