/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _15 from "./Factory.types";
import * as _16 from "./Factory.client";
import * as _17 from "./Factory.message-composer";
import * as _18 from "./Factory.react-query";
import * as _19 from "./Factory.recoil";
import * as _20 from "./Minter.types";
import * as _21 from "./Minter.client";
import * as _22 from "./Minter.message-composer";
import * as _23 from "./Minter.react-query";
import * as _24 from "./Minter.recoil";
import * as _25 from "./CwAdminFactory.types";
import * as _26 from "./CwAdminFactory.client";
import * as _27 from "./CwAdminFactory.message-composer";
import * as _28 from "./CwAdminFactory.react-query";
import * as _29 from "./CwAdminFactory.recoil";
import * as _30 from "./CwCodeIdRegistry.types";
import * as _31 from "./CwCodeIdRegistry.client";
import * as _32 from "./CwCodeIdRegistry.message-composer";
import * as _33 from "./CwCodeIdRegistry.react-query";
import * as _34 from "./CwCodeIdRegistry.recoil";
import * as _35 from "./CwSingle.types";
import * as _36 from "./CwSingle.client";
import * as _37 from "./CwSingle.message-composer";
import * as _38 from "./CwSingle.react-query";
import * as _39 from "./CwSingle.recoil";
export namespace smart {
  export namespace contracts {
    export const Factory = { ..._15,
      ..._16,
      ..._17,
      ..._18,
      ..._19
    };
    export const Minter = { ..._20,
      ..._21,
      ..._22,
      ..._23,
      ..._24
    };
    export const CwAdminFactory = { ..._25,
      ..._26,
      ..._27,
      ..._28,
      ..._29
    };
    export const CwCodeIdRegistry = { ..._30,
      ..._31,
      ..._32,
      ..._33,
      ..._34
    };
    export const CwSingle = { ..._35,
      ..._36,
      ..._37,
      ..._38,
      ..._39
    };
  }
}