/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery } from "react-query";
import { Timestamp, Uint64, Uint128, ConfigResponse, Coin, Addr, Config, ExecuteMsg, Decimal, InstantiateMsg, InstantiateMsg1, CollectionInfoForRoyaltyInfoResponse, RoyaltyInfoResponse, QueryMsg } from "./Minter.types";
import { MinterQueryClient } from "./Minter.client";
export interface MinterReactQuery<TResponse> {
  client: MinterQueryClient;
  options?: UseQueryOptions<TResponse, Error, TResponse, (string | undefined)[]>;
}
export interface MinterMintCountQuery extends MinterReactQuery<MintCountResponse> {
  args: {
    address: string;
  };
}
export function useMinterMintCountQuery({
  client,
  args,
  options
}: MinterMintCountQuery) {
  return useQuery<MintCountResponse, Error, MintCountResponse, (string | undefined)[]>(["minterMintCount", client.contractAddress, JSON.stringify(args)], () => client.mintCount({
    address: args.address
  }), options);
}
export interface MinterMintPriceQuery extends MinterReactQuery<MintPriceResponse> {}
export function useMinterMintPriceQuery({
  client,
  options
}: MinterMintPriceQuery) {
  return useQuery<MintPriceResponse, Error, MintPriceResponse, (string | undefined)[]>(["minterMintPrice", client.contractAddress], () => client.mintPrice(), options);
}
export interface MinterStartTimeQuery extends MinterReactQuery<StartTimeResponse> {}
export function useMinterStartTimeQuery({
  client,
  options
}: MinterStartTimeQuery) {
  return useQuery<StartTimeResponse, Error, StartTimeResponse, (string | undefined)[]>(["minterStartTime", client.contractAddress], () => client.startTime(), options);
}
export interface MinterMintableNumTokensQuery extends MinterReactQuery<MintableNumTokensResponse> {}
export function useMinterMintableNumTokensQuery({
  client,
  options
}: MinterMintableNumTokensQuery) {
  return useQuery<MintableNumTokensResponse, Error, MintableNumTokensResponse, (string | undefined)[]>(["minterMintableNumTokens", client.contractAddress], () => client.mintableNumTokens(), options);
}
export interface MinterConfigQuery extends MinterReactQuery<ConfigResponse> {}
export function useMinterConfigQuery({
  client,
  options
}: MinterConfigQuery) {
  return useQuery<ConfigResponse, Error, ConfigResponse, (string | undefined)[]>(["minterConfig", client.contractAddress], () => client.config(), options);
}