import pkg from '../package.json';
export const header = `/**
* This file was automatically generated by ${pkg.name}@${pkg.version}.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the ${pkg.name} generate command to regenerate this file.
*/
\n`;
